- name: Install PHP and extensions
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-fpm
    - php-mysql

- name: Ensure PHP-FPM is running
  ansible.builtin.service:
    name: php7.4-fpm
    state: started
    enabled: true

- name: Configure PHP memory limit
  ansible.builtin.lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    regexp: '^memory_limit'
    line: "memory_limit = {{ php_memory_limit }}"